redmine-5.1.4/plugins/pskb_dep_issues/config/routes.rb
# Plugin's routes
# See: http://guides.rubyonrails.org/routing.html

Rails.application.routes.draw do
  resources :pskb_dep_issues, only: [:index, :new, :show, :update, :edit, :destroy, :create]

  resources :issues do 
    member do 
      post :approve_issue
      post :reject_issue
    end
  end
end

redmine-5.1.4/plugins/pskb_dep_issues/app/models/department.rb
class Department < ActiveRecord::Base
  self.table_name = 'departments'

  has_many :issues
  attribute :name, :string
end

redmine-5.1.4/plugins/pskb_dep_issues/app/models/pskb_dep_issue.rb
class PskbDepIssue < ActiveRecord::Base
  belongs_to :users, class_name: "User", foreign_key: "user_id"
  belongs_to :departments, foreign_key: "dep_id"
end

redmine-5.1.4/plugins/pskb_dep_issues/app/controllers/pskb_dep_issues_controller.rb
class PskbDepIssuesController < ApplicationController
  layout 'admin'

  def index
    @dep_issues = PskbDepIssue.all
    @data = []
    for dep_issue in @dep_issues do 
      @data << [Department.find(dep_issue.dep_id), User.find(dep_issue.user_id), dep_issue]
    end
  end

  def new
    @dep_issue = PskbDepIssue.new
    @users = User.all
    @departments = Department.all
  end

  def create
    @dep_issue = PskbDepIssue.new(dep_issues_params)
    @dep_issue.save

    redirect_to pskb_dep_issues_path
  end

  def show
    id = params[:id]
    @dep_issue = PskbDepIssue.find(id)
  end

  def destroy
    id = params[:id]

    @dep_issue = PskbDepIssue.find(id)
    @dep_issue.destroy
    redirect_to pskb_dep_issues_path
  end

  def edit
    id = params[:id]
    @dep_issue = PskbDepIssue.find(id)
    @departments = Department.all
    @users = User.all
  end

  def update
    id = params[:id]

    @dep_issue = PskbDepIssue.find(id)
    @departments = Department.all
    @users = User.all

    if @dep_issue.update(dep_issues_params)
      redirect_to pskb_dep_issues_path
    else 
      render :edit
    end
  end

  private

  def dep_issues_params
    params.require(:pskb_dep_issue).permit(:dep_id, :user_id) 
  end
end

redmine-5.1.4/plugins/pskb_dep_issues/app/helpers/pskb_dep_issues_helper.rb
module PskbDepIssuesHelper
end

redmine-5.1.4/plugins/pskb_dep_issues/app/views/hooks/department_field/_view_issue_department.html.erb
<% if @issue.tracker_id == 1 %>
<style>

    .department-init {
        display: flex;
        align-items: center;
        justify-content: left;
        gap: 15px;
    }

    #approved_text {
        color: #13ea4e;
    }

    #reject_text {
        color: #ea1313;
    }

    #department-id {
        display: flex; /* Выстраивает "label" и "value" в одну строку, если нужно */
        gap: 15px; /* Расстояние между "label" и "value" */
    }

    #department-id .label {
        font-weight: bold
    }

    #neg-container button {
        margin-left: 5px; /* Расстояние между кнопками */
    }

    .reject-modal {
        display: none;
        position: fixed;
        background: #ffffff85;
        z-index: 1;
        left: 0;
        top: 0;
        width: 100%;
        height: 100%;
        overflow: auto;
        background-color: rgba(0, 0, 0, 0.4);
    }
  
    .reject-modal-content {
        background-color: #fefefe;
        margin: 15% auto;
        padding: 20px 20px 0px 20px;
        border: 1px solid #888;
        border-radius: 10px;
        width: 50%;
    }

    #neg-container {
        margin: 10px 0px 10px 0px;
    }

    .reject-btn{
        color: white !important;
        font-size: 15px;
        background: red;
        cursor: pointer;
    }

    .approve-btn {
        background: #34b234
    }

    .approve-btn a {
        color: white !important;
        font-size: 15px;
    }
    .approve-btn a:link, .reject-btn a:link{
        text-decoration: none;
    }
    .approve-btn a:hover, .reject-btn a:hover{
        text-decoration: none;
    }
    .approve-btn a:visited, .reject-btn a:visited{
        text-decoration: none;
    }
    .approve-btn a:active, .reject-btn a:active{
        text-decoration: none;
    }

    .reject-close-btn {
        color: black;
        font-size: 15px;
        border-size: 1000px;
        margin-top: 0px;
    }
    .reject-close-btn:hover,
    .reject-close-btn:focus {
        color: #aaa;
        text-decoration: none;
        cursor: pointer;
    }

    #reject-comment-container {
        margin: 0 auto;
    }

    .reject-actions {
        margin: 10px 10px 10px 0px;
    }

    .reject-comment {
        width: 100%;
        height: 100%;
        padding: 20px;
        border: 1px solid #ddd;
        resize: none;
        border-radius: 8px;
        background-color: #f9f9f9;
        box-shadow: 0 2px 4px rgba(0, 0, 0, 0.1);
    }

    #notify {
        color: red;
        font-size: 0.9em;
        display: none;
    }

    button:disabled {
        background-color: #ccc;
        cursor: not-allowed;
    }
</style>
<hr>
<div class="department-init">
    <div id="department-id" class="department-name">
        <div class="label">Подразделение-инициатор: </div>
        <% if !PskbDepIssue.find_by(id: @issue.department_id).nil? %>
            <div class="value"><%= Department.find(PskbDepIssue.find(@issue.department_id).dep_id).name %></div>
        <% else %>
            <div class="value">Не выбрано</div>
        <% end %>
    </div>
    <% if !PskbDepIssue.find_by(id: @issue.department_id).nil?%>
    <div id="neg-container">
    <% if @issue.status_id == ISSUES_NEGOTIATION_STAT && @issue.approved_owner.nil? && (User.current.admin? || User.current == User.find(PskbDepIssue.find_by(dep_id: @issue.department_id).user_id))%>
        <div id="reject-modal" class="reject-modal" style="display: none;">
            <div id="modal-content" class="reject-modal-content">
                <div>
                    <h2>Причина отклонения</h2>
                </div>
                <div id="reject-comment-container">
                    <textarea id="reject-comment" class="reject-comment" placeholder="Оставьте ваш комментарий"></textarea>
                    <div id="notify">Комментарий должен быть больше 5 символов!</div>
                </div>
                <div class="reject-actions">
                    <button id="reject-issue-btn" class="reject-btn">Отклонить</button>
                    <button id="reject-close-btn" class="reject-close-btn">Отменить</button>
                </div>
            </div>
        </div>
        <div class="actions-dep-btns">
            <button class="approve-btn"><%= link_to 'Согласовать', approve_issue_issue_path(@issue), method: :post %></button>
            <button id="openRejectModal" class="reject-btn">Отклонить</button>     
        </div>
    <% elsif  @issue.approved_owner == true %>
        <div id="approved_text">Согласовано руководителем подразделения</div>
    <% elsif @issue.approved_owner == false %>
        <div id="reject_text">Не согласовано руководителем подразделения</div>
    <% else %>
    <% end %>
    </div>
    <% else %>
    <div id="neg-container"><br/></div>
    <% end %>
</div>
<hr>

<script>
    const modalReject = document.getElementById("reject-modal");
    const openModalReject = document.getElementById("openRejectModal");
    const closeModalReject = document.getElementById("reject-close-btn");
    const notify = document.getElementById('notify');
    var commentArea = document.getElementById("reject-comment");

    openModalReject.addEventListener('click', function() {
        modalReject.style.display = "block";
    })

    closeModalReject.addEventListener('click', function() {
        commentArea.value = '';
        validateTextarea()
        modalReject.style.display = "none";
    })

    var rejectIssueBtn = document.getElementById("reject-issue-btn");

    function sendComment(comment) {
        const issueObj = <%= @issue.to_json.html_safe %>

        const xhr = new XMLHttpRequest()
        xhr.open('POST', `/issues/${issueObj.id}/reject_issue`, false);
        xhr.setRequestHeader('Content-Type', 'application/json');

        const csrfToken = document.querySelector('meta[name="csrf-token"]').getAttribute('content');
        xhr.setRequestHeader('X-CSRF-Token', csrfToken);

        const commentJson = {
            comment: comment
        };

        xhr.send(JSON.stringify(commentJson));

        if (xhr.readyState === 4) {
            if (xhr.status === 200) {
                window.onbeforeunload = null;
                location.reload();
            } else {
                const response = JSON.parse(xhr.responseText);
                alert(response.error);
            }
      }
    }

    function rejectIssue(event) {
        const rejectComment = commentArea.value;
        commentArea.value = '';
        sendComment(rejectComment);
    }

    rejectIssueBtn.addEventListener('click', rejectIssue);

    function validateTextarea() {
        const text = commentArea.value.trim();

        if (text === "" || text.length <= 5) {
            rejectIssueBtn.disabled = true;
            notify.style.display = "block";
        } else {
            rejectIssueBtn.disabled = false;
            notify.style.display = "none";
        }
    }

    commentArea.addEventListener('input', validateTextarea);
    validateTextarea()
</script>
<% end %>

redmine-5.1.4/plugins/pskb_dep_issues/app/views/hooks/department_field/_view_issues_form_details_bottom.html.erb
<% if @issue.tracker_id == 1 %>
  <% if @issue.status_id != PskbDomain::ISSUE_STATS[:NEG] %>
  <% else %>
    <p>
      <label for="department_id">Подразделение-инициатор</label>
      <select name="issue[department_id]" id="department_id">
        <option value="">Выберите подразделение</option>
        <% PskbDepIssue.all.each do |department| %>
          <option value="<%= department.id %>" <%= 'selected' if department.id == @issue.department_id %> >
            <%= Department.find(department.dep_id).name %>
          </option>
        <% end %>
      </select>
    </p>
  <% end %>
<% end %>

redmine-5.1.4/plugins/pskb_dep_issues/app/views/hooks/department_field/_view_issues_negotiation.html.erb
<style>
    #dep-neg-notify {
        background-color: #d2db20 ;
        text-align: center;
        font-size: 20px;
        color: white;
        border-radius: 6px;
        padding-top: 6px;
        padding-bottom: 6px;
        margin-top: 40px;
        margin-bottom: 10px;
    }
</style>

<div id='dep-neg-notify'>
    <p>Задача в процессе согласования</p> 
</div>

<% if !User.current.admin? %>
<script>
    function disableIssueEvent() {
        let contElems = document.getElementsByClassName('contextual');
        let contElemsArray = Array.from(contElems);
        contElemsArray.forEach(function(elem){
            elem.style.display = "none";
        })

        let actionsDiv = document.getElementsByClassName('actions');
        let actionsDivArray = Array.from(actionsDiv);
        actionsDivArray.forEach(function(elem){
            elem.style.display = "none";
        })

        let addNotesForm = document.getElementById('add-notes-form');
        let parentDiv = null;
        if (addNotesForm != null) {
            parentDiv = addNotesForm.closest('div');
        }

        if (parentDiv != null) {
            parentDiv.style.display = "none";
        } 
    }

    document.addEventListener('DOMContentLoaded', disableIssueEvent);
</script>
<% end %>

redmine-5.1.4/plugins/pskb_dep_issues/app/views/pskb_dep_issues/create.html.erb
<h2>PskbDepIssuesController#create</h2>

redmine-5.1.4/plugins/pskb_dep_issues/app/views/pskb_dep_issues/destroy.html.erb
<h2>PskbDepIssuesController#destroy</h2>

redmine-5.1.4/plugins/pskb_dep_issues/app/views/pskb_dep_issues/edit.html.erb
<h2>
  <%= link_to 'Подразделения', pskb_dep_issues_path %>
  >> Редактировать
</h2>

<%= form_with model: @dep_issue, method: :put, url: pskb_dep_issue_path(@dep_issue), local: true do |form| %>

  <div>
    <%= form.label :user_id, 'Voter' %>
    <%= form.collection_select :user_id, @users, :id, :name, { prompt: 'Select Voter' }, selected: @dep_issue.user_id %>
    <%= form.label :dep_id, 'Department' %>
    <%= form.collection_select :dep_id, @departments, :id, :name, { prompt: 'Select Department' }, selected: @dep_issue.dep_id %>
  </div>

  <div style="margin: 10px 0px;">
    <%= form.submit 'Изменить' %>
  </div>
<% end %>

redmine-5.1.4/plugins/pskb_dep_issues/app/views/pskb_dep_issues/index.html.erb
<div class="contextual">
  <%= link_to "Добавить подразделение", new_pskb_dep_issue_path, class: "icon icon-add" %>
</div>

<h2>Подразделения</h2>

<table class="list">
  <thead>
    <tr>
      <th>Название</th>
      <th>Владелец</th>
      <th></th>
    </tr>
  </thead>
  <tbody>
    <% @data.each do |record| %>
      <tr>
        <td><%= record[0].name %></td>
        <td><%= record[1].name %></td>
        <td>
          <%= link_to "Редактировать", edit_pskb_dep_issue_path(record[2]), class: "btn btn-warning" %>
          <%= link_to "Удалить", pskb_dep_issue_path(record[2]), method: :delete, data: { confirm: "Вы уверены?" }, class: "icon icon-del" %>
        </td>
      </tr>
    <% end %>
  </tbody>
</table>

redmine-5.1.4/plugins/pskb_dep_issues/app/views/pskb_dep_issues/new.html.erb
<h2>
  <%= link_to 'Подразделения', pskb_dep_issues_path %>
  >> Создать
</h2>
<%= form_with(model: @dep_issue, url: pskb_dep_issues_path) do |form| %>

  <div>
    <%= form.label :user_id, 'Voter' %>
    <%= form.collection_select :user_id, @users, :id, :name, { prompt: 'Select Voter' } %>
    <%= form.label :dep_id, 'Department' %>
    <%= form.collection_select :dep_id, @departments, :id, :name, { prompt: 'Select Department' } %>
  </div>

  <div style="margin: 10px 0px;">
    <%= form.submit 'Создать' %>
  </div>
<% end %>

redmine-5.1.4/plugins/pskb_dep_issues/app/views/pskb_dep_issues/show.html.erb
<h2>Подразделение</h2>

<div>
    <%= @dep_issue.id %>
    <%= @dep_issue.dep_id %>
    <%= @dep_issue.user_id %>
</div>
<%= delete_link pskb_dep_issue_path(@dep_issue)%>
<%= link_to 'Редактировать', edit_pskb_dep_issue_path(@dep_issue) %>

redmine-5.1.4/plugins/pskb_dep_issues/app/views/pskb_dep_issues/update.html.erb
<h2>PskbDepIssuesController#update</h2>