redmine-5.1.4/plugins/pskb_domain/config/routes.rb
# Plugin's routes
# See: http://guides.rubyonrails.org/routing.html
# Plugin's routes
# See: http://guides.rubyonrails.org/routing.html

Rails.application.routes.draw do
  resources :pskb_obj_type, only: [:index, :new, :show, :update, :edit, :destroy, :create]

  resources :pskb_negotiation_stat, only: [:index, :new, :show, :update, :edit, :destroy, :create]
end

redmine-5.1.4/plugins/pskb_domain/app/models/negotiation.rb
class Negotiation < ActiveRecord::Base
end

redmine-5.1.4/plugins/pskb_domain/app/models/negotiation_stat.rb
class NegotiationStat < ActiveRecord::Base
end

redmine-5.1.4/plugins/pskb_domain/app/models/pskb_obj_type.rb
class PskbObjType < ActiveRecord::Base
end

redmine-5.1.4/plugins/pskb_domain/app/controllers/pskb_negotiation_stat_controller.rb
class PskbNegotiationStatController < ApplicationController
  layout 'admin'

  def index
    @pskb_neg_stats = NegotiationStat.all
  end

  def new
    @new_neg_stat = NegotiationStat.new
  end

  def create
    id = params[:id]

    @new_neg_stat = NegotiationStat.new(pskb_neg_stats_params)
    if @new_neg_stat.save
      redirect_to pskb_negotiation_stat_index_path
    end
  end

  def show
    id = params[:id]
    @pskb_neg_stat = NegotiationStat.find_by(id: id)
    if @pskb_neg_stat.nil?
      render_404
    end
  end

  def destroy
    id = params[:id]
    @pskb_neg_stat = NegotiationStat.find_by(id: id)
    if @pskb_neg_stat.nil?
      render_404
    end
    if @pskb_neg_stat.destroy
      redirect_to pskb_negotiation_stat_index_path
    end
  end

  def edit
    id = params[:id]
    @pskb_neg_stat = NegotiationStat.find_by(id: id)
    if @pskb_neg_stat.nil?
      render_404
    end
  end

  def update
    id = params[:id]
    @pskb_neg_stat = NegotiationStat.find_by(id: id)
    if @pskb_neg_stat.nil?
      render_404
    end
    if @pskb_neg_stat.update(pskb_neg_stats_params)
      redirect_to pskb_negotiation_stat_index_path
    end
  end

  private 

  def pskb_neg_stats_params 
    params.require('negotiation_stat').permit(:name)
  end
end

redmine-5.1.4/plugins/pskb_domain/app/controllers/pskb_obj_type_controller.rb
class PskbObjTypeController < ApplicationController
  rescue_from ActiveRecord::RecordNotFound, :with => :render_404

  layout 'admin'

  def index
    @obj_types = PskbObjType.all
  end

  def new
    @new_obj_type = PskbObjType.new
  end

  def create
    params = pskb_type_obj_params

    @new_obj_type = PskbObjType.new(params)
    if @new_obj_type.save 
      redirect_to pskb_obj_type_index_path
    else
      Rails.logger.info("NOT OK")
    end
  end

  def show
    id = params[:id]
    @pskb_obj_type = PskbObjType.find_by(id: id)
    if @pskb_obj_type.nil?
      render_404
    end
  end

  def destroy
    id = params[:id]
    @obj_type = PskbObjType.find_by(id: id)

    if @obj_type.nil?
      render_404
    end

    if @obj_type.destroy
      redirect_to pskb_obj_type_index_path
    end
  end

  def edit
    id = params[:id]
    @pskb_obj_type = PskbObjType.find_by(id: id)

    if @pskb_obj_type.nil?
      render_404
    end
  end

  def update
    id = params[:id]
    @pskb_obj_type = PskbObjType.find_by(id: id)
    if @pskb_obj_type.nil?
      render_404
    end

    if @pskb_obj_type.update(pskb_type_obj_params)
      redirect_to pskb_obj_type_index_path
    end
  end

  private

  def pskb_type_obj_params 
    params.require('pskb_obj_type').permit(:name, :description)
  end
end

redmine-5.1.4/plugins/pskb_domain/app/helpers/pskb_negotiation_stat_helper.rb
module PskbNegotiationStatHelper
end

redmine-5.1.4/plugins/pskb_domain/app/helpers/pskb_obj_type_helper.rb
module PskbObjTypeHelper
end

redmine-5.1.4/plugins/pskb_domain/app/views/pskb_obj_type/create.html.erb
<h2>PskbObjTypeController#create</h2>

redmine-5.1.4/plugins/pskb_domain/app/views/pskb_obj_type/destroy.html.erb
<h2>PskbObjTypeController#destroy</h2>

redmine-5.1.4/plugins/pskb_domain/app/views/pskb_obj_type/edit.html.erb
<h2>
  <%= link_to 'Типы объектов PSKB', pskb_obj_type_index_path %>
  >> Редактировать
</h2>

<%= form_with model: @pskb_obj_type, method: :put, url: pskb_obj_type_path(@pskb_obj_type), local: true do |form| %>

  <div>
    <%= form.label :name, 'Name' %>
    <%= form.text_field :name %>

    <%= form.label :description, 'Description' %>
    <%= form.text_field :description %>
  </div>

  <div style="margin: 10px 0px;">
    <%= form.submit 'Изменить' %>
  </div>
<% end %>

redmine-5.1.4/plugins/pskb_domain/app/views/pskb_obj_type/index.html.erb
<div class="contextual">
  <%= link_to "Добавить тип объекта PSKB", new_pskb_obj_type_path, class: "icon icon-add" %>
</div>

<h2>Типы объектов PSKB</h2>

<table class="list">
  <thead>
    <tr>
      <th>Название</th>
      <th>Описание</th>
      <th></th>
    </tr>
  </thead>
  <tbody>
    <% @obj_types.each do |record| %>
      <tr>
        <td><%= record.name %></td>
        <td><%= record.description %></td>
        <td>
          <%= link_to "Редактировать", edit_pskb_obj_type_path(record), class: "btn btn-warning" %>
          <%= link_to "Удалить", pskb_obj_type_path(record), method: :delete, data: { confirm: "Вы уверены?" }, class: "icon icon-del" %>
        </td>
      </tr>
    <% end %>
  </tbody>
</table>

redmine-5.1.4/plugins/pskb_domain/app/views/pskb_obj_type/new.html.erb
<h2>
  <%= link_to 'Типы объектов PSKB', pskb_obj_type_index_path %>
  >> Создать
</h2>
<%= form_with(model: @new_obj_type, url: pskb_obj_type_index_path) do |form| %>

  <div>
    <%= form.label :name, 'Название' %>
    <%= form.text_field :name %>

    <%= form.label :description, 'Описание' %>
    <%= form.text_field :description %>
  </div>

  <div style="margin: 10px 0px;">
    <%= form.submit 'Создать' %>
  </div>
<% end %>

redmine-5.1.4/plugins/pskb_domain/app/views/pskb_obj_type/show.html.erb
<h2>PskbObjTypeController#show</h2>

redmine-5.1.4/plugins/pskb_domain/app/views/pskb_obj_type/update.html.erb
<h2>PskbObjTypeController#update</h2>